### ISSUE TITLE
interaction camera for AAF deployment

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#16]
We need to mount a webcam (and connect it to werner-right-cortex) to record people interacting with Henry. This cannot run continuously, but only when we are at permitted nodes. Hence a dedicated node that monitors the `/current_node` topic and switches recording on or off needs to be developed. Rather then stopping the recording, we should switch it to record a "black" image, by using [mux](http://wiki.ros.org/topic_tools/mux) to switch between the real image stream and a dummy image stream to be provided by the component itself.

The whole implementation should be based on [usb_cam](http://wiki.ros.org/usb_cam) and [data_compression](https://github.com/strands-project/data_compression), plus [topic_tools/throttle](http://wiki.ros.org/topic_tools/throttle) to reduce the framerate to 0.5 Hz.

**Comment by marc-hanheide** [comment]
assigned to @mzillich to make sure the camera is obtained and mounted. Once this is done, I look for volunteers to implement the component (or I'll do it myself). I seek input from @nilsbore (on data_compression), and @cdondrup, @yianni, and @denisehe for the general implementation of this functionality.

**Comment by hawesie** [comment]
I believe @kunzel has some code for detecting when a robot is in a region.

**Comment by denisehe** [comment]
Hey,
in regard of the additional camera it would be important for us that it is facing towards Henry's back and thus records users while they interact with the robot.

The camera should get the head (most important) and eventually torso of the user. Futhermore it would be nice to see if it is just one user or if there are more people interacting with the robot. Thus iv the camera could sourveille a broader angle it would be great!

And the camera should not be moving, or change its possition after detecting an user interacting with the robot as this might is distracting!

I am also not sure if you already chose a camera type - but the smaller and unobstrusive the better!

Best Wishes

Denise

**Comment by marc-hanheide** [comment]
@nilsbore could you provide an estimate on the amount of data to expect and how to use it, please

**Comment by nilsbore** [comment]
If we assume that the images are 640x480 (same as Kinect) then ROS image compression (I forget if it's png or jpeg) would give us about 1.5 GB at 1 FPS for 12h. The same number for theora image transport would be about 100 MB. Both formats are lossy with theora being worse. In this file: `https://github.com/strands-project/data_compression/blob/hydro-devel/mongodb_openni_compression/launch/record.launch` the compression and logging of depth/rgb images are launched separately so that gives a good idea of how to use compression/logging. Note that the argument `rgb_compression` can be changed from `compressed` (image compression) to `theora` (theora video compression).
