### ISSUE TITLE
AAF testing

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#168]
- [x] new topo map
- [x] regular info terminal
- [x] scheduled walking group
- [x] scheduled info_task
- [x] scheduled bellbot
- [x] emergency stop
- [ ] staff interface
- [x] data upload task

@Jailander @cdondrup @mzillich @denisehe

**Comment by marc-hanheide** [comment]
tick off the things we tested an comment below for observations

**Comment by denisehe** [comment]
ok!

**Comment by denisehe** [comment]
could you also assign tobias to this issue!

**Comment by cdondrup** [comment]
@TobKoer

**Comment by cdondrup** [comment]
- topo map: Still need to move the "Cafeteria" waypoint but need to wait until the furniture is back where it belongs. Influence areas need to bigger for most of the waypoints.
- scheduled bellbot, info_terminal, and emergency behaviours will be tested on Thursday by @Jailander and @TobKoer, given the scheduler works again.
- walking group was tested without the scheduler. Will add a page when the robot is waiting for the therapist to come closer to give feedback that it is waiting deliberately and not just stopped due to navigation issues.

Since the scheduler didn't work, most of the things couldn't be tested, but the basics look fine.

**Comment by TobKoer** [comment]
We'll do another test-run for the bellbot at AAF with Jaime and Wolfgang tomorrow.

**Comment by marc-hanheide** [comment]
@cdondrup is my list of tasks at https://github.com/strands-project/aaf_deployment/wiki#tasks-that-can-be-scheduled complete and correct? These should be the tasks we put in the google calendar to see them being scheduled and executed in the test, IMO.

**Comment by cdondrup** [comment]
The bellboy task is actually called `bellbot_launch` which is quite unintuitive, so we could change it.

**Comment by cdondrup** [comment]
setting max duration of info_task doesn't work.

**Comment by cdondrup** [comment]
data is not replicated but task succeeded. Wrong collections or wrong times.

**Comment by cdondrup** [comment]
bellbot, doesn't work. See gitter.

**Comment by cdondrup** [comment]
In go_to_safety_node free run is not enabled.

**Comment by TobKoer** [comment]
Hi, cdondrup has already commented on the test runs, but quickly from my side:
most issues tested, but scheduler not working; bellbot not working; issues with bellbot display (usability almost zero for older users or people not used to touch screen menus);
- bellbot: display still a mix of German and English
- bellbot: remove status guiding with map and instead show direction arrows (like in the walking group?)
- task hierarchy apparently not working reliably?
- robot position not always useful for info-terminal (i.e. screen facing towards wall)
