### ISSUE TITLE
[AAF deploy] - voice outputs

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#173]
Hey @marc-hanheide - are the voice outputs actually already implemented?

Cheers Denise 

@TobKoer

**Comment by marc-hanheide** [comment]
nope...

**Comment by denisehe** [comment]
We think that has to be done on some point before the real deployment as some feedback is required.

**Comment by marc-hanheide** [comment]
Then please prioritise for me which ones are most urgent.

**Comment by TobKoer** [comment]
I haven't heard any so far, but what is of high priority is:
- emergency (robot asking for help)
- robot canceling a task or idle behaviour in order to start another task (i.e. the robot should say something/indicate why it is driving off instead of just driving off. This is very irritating when using the robot as info-terminal)
- recovery behaviour: the robot should explain that it is doing something, otherwise users do not know if it is hung-up or what is happening
- possibly the robot should also say "Thank you for using the bellbot service" or something similar at the end of the bellbot scenario (in german, of course)

Let me kow if we should provide you with German texts for voice-outputs.

Cheers.

**Comment by denisehe** [comment]
hey I have to leave early today, I sent tobias the list of voice outputs and he will prioritice things!

**Comment by TobKoer** [comment]
Okay, I'll try:
1. Info-terminal ending/robot driving off
2. Recovery-behaviour (so far, we haven't planned for this, but robot should indicate what is happening, e.g. "Please wait. I am currently re-starting"... or something like that.
   3.Robot asking for help
3. Bellbot procedure voice outputs + thanks at the end 
4. stopping during patrolling for info-terminal
5. engaging people to interact

all of this is in the list from Denise, apart from recovery-behaviour.

**Comment by TobKoer** [comment]
Hi;
any news on this. Implementation status?
Cheers.

**Comment by cdondrup** [comment]
> Info-terminal ending/robot driving off

Already working on robot

---

> Recovery-behaviour

Has been localised to german already

---

> Bellbot procedure voice outputs + thanks at the end

I could write a node that listens to the state and says text based on a config file, might be better than hard coding it in the state machine. Any better ideas @marc-hanheide @Jailander ?

---

> stopping during patrolling for info-terminal

Currently the robot won't stop I'm afraid.

---

> engaging people to interact

There is no engagement

---

> robot canceling a task or idle behaviour in order to start another task

Already working **Edit**: If the task has to be carried out at a different waypoint. If it is the same waypoint there is no need to do anything imho.

**Comment by marc-hanheide** [comment]
Yes, a little component that listens on the state is preferable for bellboy voice output.
