### ISSUE TITLE
human-aware navigation at AAF

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#25]
the local navigation needs to be 100% bullet proof in the presence humans. So this is about finding suitable parameters.

**Comment by hawesie** [comment]
Also, true for security. Oddly this was the first thing I thought about when I woke up this morning. We should find that bullet-proof set of parameters and run them everywhere. My initial suggestion for reliability is a slow robot.

**Comment by cdondrup** [comment]
By parameters you mean tweaking the local planner? No extra behaviour when crossing edges, right? Or should it be a dedicated node that sets these parameters?

**Comment by marc-hanheide** [comment]
I'm not sure about the best way here to be honest. I think most importantly it's about the right parameters and costmaps to be used. And making human aware navigation to change e.g. the rotation parameters and available recovery behaviours. E.g. when being stuck when humans are present a different recovery is suitable then in their absence.

**Comment by cdondrup** [comment]
Good point, the thing about restricting the rotation is, that the planner then goes straight and drives into obstacles because it does not seem to be aware of the restrictions of the rotational speed. At least this is what we observed at last years deployment and which is why I disabled the restriction of the rotational speed.
Maybe I was missing something, I will have a look again.

Regarding the recovery behaviours, this should be doable, because one can add recovery behaviours using a simple service call. The only thing I don't know is if you can disable them as well. Maybe @bfalacerda has some insight there.

**Comment by bfalacerda** [comment]
There are different ways of doing this:
1. If you want a very different recovery behaviour, use the [`/monitored_navigation/set_nav_recovery`](https://github.com/strands-project/strands_navigation/blob/topological-testing/strands_navigation_msgs/srv/SetNavRecovery.srv) and set a new smach recovery state machine with the new logic for that particular recovery behaviour. This service can only be used when monitored_navigation actions server is not active (otherwise we would be editing a smach sm while it's being executed), so setting new recoveries when humans are detected for example requires some extra effort on preempting the action and then send the goal again. 
2. If the change is something more direct (e.g., if there's humans don't backtrack), one can just add an `active` param in the backtrack state, and set it using rosparam. This can be done during execution of the monitored_navigation state machine.

For this particular problem, I like option 2. better. Option 1. is more useful to hard-code changes in recovery behaviours on certain topological edges (which we are also in the process of implementing)

**Comment by cdondrup** [comment]
Cancelling the goal, changing the recovery behaviours, and resending it sounds like a bit of a hack. I do like the second solution better as well but that would mean that 
- every recovery behaviour would have to offer such a parameter 
- or the mon nav should offer a parameter where one could set and get the activated behaviours as a list. 

I think I would prefer the latter over having to call every recovery behaviours parameters since I don't really know which ones are active in the first place, or do I? With this I could give it a blacklist of behaviours I don't want to have, get the currently running ones, remove the blacklisted, reconfigure, and restore the previous settings after no humans are there any more.

**Comment by cdondrup** [comment]
Also, it would be great to add recovery behaviours to the config file stating that they should start as `inactive` and can only be activated via dynamic reconfigure. This way we could have custom ones that we don't have to add dynamically but just turn on when we need them. This would mean a list of all available behaviours via a parameter would also be necessary.

Would this be possible?

**Comment by bfalacerda** [comment]
It is possible, but not implemented right now. I could get some interfaces for that but only next week. I'll open a ticket in strands_navigation and assign myself.

The main issue right now is that what we are referring to as recovery behaviours are in fact smach states in the nav recovery state machine, so they don't really have any kind of pre-defined interface (only the overall recovery state machine has those).
