### ISSUE TITLE
Legibility of Robot Behavior

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#26]
Hey, 

as I could not follow your answers during todays hangout calls => is somebody working on reobot legibility by now?
=> making the robots behavior more legibel?

Important issues would be:

Henry indicating to go around a cornder
Henry going backwards (alermsound)
Henry announcing to leave a certain place or ends a certain task (f.e. HRI takes place and another tasks with higher priority interrupts inbetween)

**Comment by marc-hanheide** [comment]
@cdondrup might have something to say on this?

**Comment by marc-hanheide** [comment]
We have a student working on indicators, as known from cars. We _might_ have a solution to this that we _could_ integrate, but no promises yet. It might interesting to do it this year without and present it as an improvement next year.

**Comment by cdondrup** [comment]
We have the general aim of having arrows on the display indicate the direction the robot is going when guiding the walking group. @santosj is looking into that after the IROS deadline is over. This could then also be used to control the indicators, but as @marc-hanheide said, there is a lot of could, would, and should in there. Instead of the indicators we can also try and use the gaze direction of the robot to substitute the indicators, but that would ba a bit more subtle and might not be noticeable if your vision is impaired.

Regarding the other two points:
- We do have a behaviour where he goes backwards and says to please go out of the way. This could be substituted via a alarm sound without problems. The bigger issue here is, that the robot does not always go backwards after saying that. But playing an alarm sound might still be a good idea. The only problem is to make the link between the sound playing and the robot going backwards. So I think a combination of speech and the sound would be best.
- Imho the scheduler would have to take care of the last of your points because we cannot assume that every action it executes provides an audio output when it is preempted or has succeeded. Or maybe it is better to this whenever the robot gets a new navigation goal, @Jailander @bfalacerda ?!

**Comment by Jailander** [comment]
I don't see any problem with sending a topic every time the robot gets a new navigation goal so another module can play a sound (I wouldn't play a sound directly as navigation should be independent from these things)

**Comment by cdondrup** [comment]
The only problem is, that this would have to be done before the robot starts moving, including a time delay to give people time to react. This is why the scheduler might be better, because the navigation instantly starts moving the robot when a goal is received. This would be the same behaviour as last year which wasn't too nice.

**Comment by Jailander** [comment]
yes in that case it better if handled by the scheduler directly unless @bfalacerda has any other idea

**Comment by cdondrup** [comment]
@mudrole1 @hawesie would that be possible? Otherwise, I wouldn't know where to put it.

**Comment by marc-hanheide** [comment]
To be honest, I don't think you need much of a delay. We could (optionally) have navigation call a service `prepare_movement` that will be called before the motion actually starts and only when it returns `True` the motion will actually go ahead. This service can then play a sound and introduce any delays deemed needed.

**Comment by bfalacerda** [comment]
I agree with using the task executive (not exactly the scheduler in this case) to do the talking, as it clearly splits each task into a navigation to a waypoint, and an execution of an action server once the waypoint is reached. It should be quite easy to add a call to mary before starting to move

**Comment by marc-hanheide** [comment]
just not sure: are we _always_ going via task_executive before moving, e.g. the bellbot, doesn't it move _within_ a single task? I still find it clearer and better separated if we have an optional function in navigation, because also this function can check conditions, e.g. getting confirmation to be allowed to bugger off...

**Comment by bfalacerda** [comment]
True, I was thinking of last years system. The higher level that can be called directly to make the robot move is monitored nav, so I guess this is another job for me. Next week :)

**Comment by Jailander** [comment]
not necesarily @bfalacerda topological_navigation or policy execution should do it (not that I want to take work from you for myself :P ) but if you do it in monitored_navigation it would also sound between nodes where the robot hasn't even stopped, whilst the topological navigation level can do it for the whole plan.

**Comment by bfalacerda** [comment]
Right. I was thinking that the info terminal does direct calls to monitored navigation but it goes through the whole demand task procedure. It should be ok to out it in topological nav then

**Comment by Jailander** [comment]
Ok, but stupid question why does the terminal use monitored navigation directly?

**Comment by bfalacerda** [comment]
Ignore my last comment, in the info terminal there is a call to monitored_navigation that bypasses topological: When a person is detected waving to the robot while it is navigating to a task, we demand a task that first drives towards the person who waved, and then starts the info terminal gui. We use monitored here because it's navigation to a pose that is not a waypoint.

However, since we plan to acknowledge the person after detection in the info_terminal, it still should be ok to have the talking done at the topological navigation level, and treat this special case in its own action server.

So, I think we're ok following @marc-hanheide 's  suggestion of using a `prepare_movement` service at the topological navigation/ policy executor level
