### ISSUE TITLE
[walking-group] therapists click wrong buttons

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#270]
turns out the therapists are even less reliable than the robot :smile: 

They pressed "Abbruch" after 15 minutes into the tour and carried on without the robot...

@cdondrup we need to take this option out, I think.

right @denisehe ?

**Comment by lobinho** [comment]
I think at least a prompt to confirm would be a good idea.

**Comment by marc-hanheide** [comment]
I have temporarily removed that button from the GUI...

**Comment by lobinho** [comment]
I asked the therapist after the session and she said that neither she nor a patient clicked Abbruch. But she was not 100% sure..

I also want to mention that I heard somebody clicking and then the music started playing just for like half a second. Then the music stopped and the menu did not respond anymore. It seems like the task had stopped. 
I don't know, what would happen, if Abbruch was clicked? Would the music even start playing? Because it was playing definitely.

**Comment by marc-hanheide** [comment]
I'm pretty sure "Abbruch" was clicked. The logs all point  that way. Maybe after the started the music accidentally. It's a touch screen, so things like this can easily happen. As I said, I disabled that "fatal" button.

**Comment by TobKoer** [comment]
@marc-hanheide @lobinho @denisehe 
So, what if something happens in the group now. Shall we tell therapists to simply abandon the robot?
I think this happened once before, when some resident simply walked off and had to be searched for by therapists. In this case now, there is no way to tell the robot that the walking group is cancelled and it will just keep standing somwhere?

**Comment by denisehe** [comment]
probably a confirming button would be best!

**Comment by marc-hanheide** [comment]
yes, probably would, but I have no time to implement this any time soon. As we are remotely with the robot anyway, we can still cancel this if needed.

**Comment by TobKoer** [comment]
@denisehe 
agreed!
