### ISSUE TITLE
[info-terminal] RSS reader

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#28]
@denisehe has suggested that the headline news from Vienna, Austria, and the World should be displayed. This IMO should be done by getting the RSS feed from ORF:
- http://rss.orf.at/news.xml
- http://rss.orf.at/oesterreich.xml
- http://rss.orf.at/wien.xml

**Comment by cburbridge** [comment]
The "events" page currently takes the top 3 entries from BBC RSS feed, so this is no problem. However, this was just a place holder I created for the in-house events page. Should the ORF headlines be displayed on the events page, or where?

**Comment by marc-hanheide** [comment]
In addition we need to display the local news: https://henrystrands.wordpress.com/feed/ probably side by side?

**Comment by cburbridge** [comment]
This is what is looks like now with just three items from the BBC RSS feed. How should I lay it out to get the extra information in there?:
![events](https://cloud.githubusercontent.com/assets/259580/6906833/1ef014fa-d729-11e4-9d44-63dfc7b78364.png)

**Comment by marc-hanheide** [comment]
What about making it two columns and putting the back button at the bottom, less tall, but full width?

**Comment by cburbridge** [comment]
![events](https://cloud.githubusercontent.com/assets/259580/7076663/d6a4b1b0-df02-11e4-9a84-7593261e3243.png)

You can test it from my branch: https://github.com/cburbridge/aaf_deployment/tree/events

The ORF news feeds don't provide nice thumbnails. Also the wordpress blog feed provides HTML formatted entries that can mess up the layout, you will need to make sure they are large font and well scaled graphic etc manually for each entry.

Also, the screen space is very limited and this won't fit on the robot screen like this, mostly because of the wordpress articles....

**Comment by marc-hanheide** [comment]
OK, what about stripping out only the description from the RSS of WordPress? No images etc...
