### ISSUE TITLE
adaptation of walking group

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#288]
https://docs.google.com/document/d/16a7nOE-UchIGuOqc9v7XzLY1ZqCxY6rl4PqxY0NJ6CE/edit?usp=sharing
- [x] check if videos are needed and if make them work

**Comment by denisehe** [comment]
Hi all together. I talked to the therapists and they are available on Monday, 8th of February at 1pm or half an hour to talk about the robot :-)

@marc-hanheide @cdondrup @TobKoer

**Comment by marc-hanheide** [comment]
:+1: That's good. Let's hope half an hour is enough...

**Comment by cdondrup** [comment]
We'll make the most out of it. Thank you!

**Comment by marc-hanheide** [comment]
- photos from actual events (get them from the Wards, @denisehe to upload)
- adaptive speed: dial on screen
- interaction more map-based, display map while going along, and enable the admin interface to select next waypoint, also show the route
- consistent back button at every GUI screen
- enable free run with big button for admins and any time
- volume buttons when playing music
- plan a pre-run
- notification for therapist ("out of order")

**Comment by marc-hanheide** [comment]
@TobKoer @denisehe please add your comments

**Comment by denisehe** [comment]
*therapist should be able to select the music trac they want to start with after the break
*interaction map on the resting point where therapists can select to which chair the robot should move (this should happen after the beginning of the pause - asking that streight away (before the break) would not make sence, as not all people would not be seated yet)
*Video option can be deleted
*BACK-button in the administration site (waypoint list - in future map)

**Comment by cdondrup** [comment]
TODOs:

Please remind me if I forgot an important point.

Important:
- [x] Map view for selecting specific resting areas
- [x] Map view of each resting are to select chairs to park robot in front of
- [x] "Out of order" web page to be triggered remotely when something breaks 
- [x] "Trying to recover" webpage when recovery behaviour triggered. @bfalacerda is there a way of knowing this?
- [x] Add volume buttons to entertainment interface

Nice to have:
- [x] Switch buttons to `onmousedown` instead of `onclick` in case patients don't let go.
- [x] Make video work (or delete if not feasible)
- [ ] Select which song to play
- [x] Add more explicit "back button" to admin interface. It already has a button to switch to the entrtainment interface and the "Weiter" button goes back to navigation.

Experimental:
- [ ] Adaptive speed based on distance to therapist

**Comment by TobKoer** [comment]
Hi -
that's also what I had on my list.

**Comment by TobKoer** [comment]
@cdondrup 
Hi - just out of curiosity: is there any way to influence the runiing order of MP3s in the music group. I've uploaded new soundfiles now, but the UI (192.168.200.20/werner/setup) always creates its own running order for tracks.
Or will the music tracks now be played in random order anyway during the walking groups?

**Comment by cdondrup** [comment]
Most of the requested features have been implemented in https://github.com/strands-project/aaf_deployment/pull/315 except for the "trying to recover" feature as I don't have feedback about this from the robot itself. @bfalacerda and @Jailander Is there any way to find out if a recovery behaviour is triggered?

Also, the video has been removed because I didn't have time to look into this yet and we agreed that it is not crucial. 

Selecting which song to play would be nice to have but the effort to implement this far outweighs its usefulness I'm afraid. Simply changing the selection of songs on the media server once in a while should be good enough I think. @TobKoer please remember to add the songs you upload to the `aaf_walking_group_music` set which you can find under "Music Sets". Just click on edit and add the songs you like. I think that the order is either alphabetical or random. Not entirely sure.

Regarding the adaptive speed: No.

**Comment by cdondrup** [comment]
I had a look at the video playback again. When starting the video the media server consumes about 60% CPU for a second or two, afterwards it is stable at ~1%. While it is running, firefox uses ~20% CPU. The memory usage of both is negligible around 1% or less. All this is on my machine which is slightly higher spec than Werner...

I think we should test this again on Monday to see where the actual problem with the video is. I will add the video button again and then we can check it live on the robot.

**Comment by cdondrup** [comment]
@TobKoer As a compromise for the music playback, the songs are now shuffled (see above PRs) every time a new walking group starts. this should at least prevent that the therapists now the order of songs by heart after the first week ;)

Also, when adding songs, please make sure that the file name does not contain spaces and special symbols like Umlaut, apostrophes, etc. This is just to prevent the system from breaking because it does not interpret the filename correctly.

**Comment by cdondrup** [comment]
OK, also implemented some form of "trying to recover" feedback for the therapists.

**Comment by cdondrup** [comment]
New minor improvements to walking group:
- [x] Add two more waypoints to the Kapelle resting area
- [x] Add a button to go to the chair selection from the admin interface. Should only work if the robot is at a resting point.
- [x] Lower camera angle so it sees the card even if the therapist is close to the robot
- [ ] If the Teekueche is not chosen as a resting area, make the robot go "the short way"
- [x] Have two buttons at Ambulanz and Frisoer to make it explicit if the robot should go there on the way there or back.

**Comment by denisehe** [comment]
ah and i remember on other issue, i think I also know now why it occured

when returning to rast 2 on the way back, the robot goes very far away, towards the lobby from the chairs asking "weiter/rast"...

but i think thats cause this is the resondable waypoint during the starting phase where the group reaches the seats from the lobby.

**Comment by denisehe** [comment]
and at one waypoint next to the chairs at Rast 2, if u stand in front of the chairs, on the right side, the robot danced around some times, going to the waypoint, circling, driving out and waved back in...but thats maybe more an navigation issue?

**Comment by cdondrup** [comment]
The first one should be solved by implementing multiple buttons for the cafeteria. The problem there was that there are two different points where the robot asks if you want to rest depending on where you're coming from. It just chose the wrong one because it was confused.

The other one sounds like anavigation issue. If that happens again, let me know.

**Comment by denisehe** [comment]
ok!

yes, i will!

**Comment by cdondrup** [comment]
@denisehe See #321

I implemented everything but the shorter route. That wouldn't be easy and I think there is not much harm in walking an additional 10 meters ;)
Sorry, but I couldn't do that in the time I had.

**Comment by cdondrup** [comment]
Also, the route planning was improved. You now can choose what ever waypoint you want at every point during the group and get the correct behaviour.

**Comment by denisehe** [comment]
very nice - looking forward to testing that tomorrow :)
