### ISSUE TITLE
[info-terminal] stop on touch

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#29]
The idea (conveyed by @denisehe)  is that Henry should also stop (only when in info terminal patrol mode) not only when being waved at but also when somebody touches the display. So effectively this should have the same effect as waving at Henry, when somebody touches him while moving or standing. E.g. look at http://stackoverflow.com/questions/8054429/how-do-i-handle-a-click-anywhere-in-the-page-even-when-a-certain-element-stops.

Assigned to @mzillich to comment and then assign to the right person in his team ;-)

**Comment by cburbridge** [comment]
While the robot is moving between info-terminal positions @denisehe would like the robot to be showing a slideshow of the photos in the photo-album, auto transitioning between images. It is on this screen that the click-anywhere needs to stop the robot, so this screen needs creating first. Will this screen be only active when moving between info-terminal points, or is it supposed to be the default screen throughout the deployment?

**Comment by cdondrup** [comment]
Please keep in mind that the robot might also have to move slower in order to do this. First because you might not be able to catch it otherwise and second  if it stops from full speed that might be too abrupt and dangerous for people chasing after it.

**Comment by marc-hanheide** [comment]
We will be going very slowly anyway (in particular in info-terminal mode?)

**Comment by denisehe** [comment]
Well the idea was that if people follow the robot, looking at the displayed slide show do also have the possibility to stop the robot to gain more information. this would be easyest by touchting the screen rather than quickly overtaking the robot and trying gestures and gaze to stop the robot.

Thus it would be nice for users to stop the robot a) from the front: waving/looking at the robot and b) from the back: touching the screen directly.

This would be required during the patrolling task. 

If Henry stands somewhere offering the Infoterminal by himself I think the infoterminal mainscreen should be displayed.

Thus interupting the slideshow would just occur if the robot is on patrol and some users would gain information.
