### ISSUE TITLE
Walking Group - adaptive waiting

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#334]
Hey @cdondrup 

during yesterdays walking group I became aware that the robot does not wait for the therapists anymore if they fall back on an adaptive basis (card and distance) but that he continues to the next fixed waiting point.

So I was a bit confused cause I always explain the therapists that the robot needs the lenyard to detect them and to wait if they are to far away. but as he did not wait therapist were also confused.

I asked Wolfang and he said that this was changed because of the wish of therapists that he does not wait to often.

But I think the "wait to often" did not refere to the adaptive waiting but to the many fixed waypoints the robot was stoping at alghough the group was right there (where you reduced numbers, which showes really beneficial this year).

so my question: what happened to the adaptive waiting?

Best wishes - Denise

**Comment by cdondrup** [comment]
I am sorry to disappoint but there never was an adaptive waiting. In the first implementation of the walking group, the robot would wait after a fixed distance, e.g. 5m, until it sees the control card in a certain distance and then show the "Weiter" button. The therapists complained that that was too often and asked if that could be changed to waiting only once between each resting point. This is why it currently waits at always the same position between each of the resting points until it sees the card in <4m distance and then shows "Weiter".

I am not sure which behaviour you refer to but I assure you that there never was any adaptive waiting.

I could implement something like this:

If the robot does not see the card within 4m distance for ~10s it will wait until it sees the card again and then drive off without any other need for interaction. There would be no "Weiter" button but it would just continue because the button would be a bit too annoying I reckon.

The only problem with that is, in cases like yesterday, where two patients were following the robot without having a card around their neck, hiding the therapists behind them, the robot would not move. So a therapist would have to walk behind the robot at all times.

**Comment by TobKoer** [comment]
from Denise: hmmmm interesting I thought it was adaptive waiting also.

**Comment by TobKoer** [comment]
i have to think about it but yes i alsways thought that it was adaptive....
yes so like this I also udnerstand why u said u reduced the waiting points because of to much waitng...and that this is tied to the waiting for the group in general

i will also tell the therapists...well we just had the issue last monday...lets see how it goes today

ah and could we put a new video in from one of this years walking groups?

**Comment by cdondrup** [comment]
The video is up to @marc-hanheide I will open an issue for that. Let me know if you want me to do anything about this issue.
