### ISSUE TITLE
Create walking group videos and upload to media_server

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#338]
From the log data of this year, it would be great if we could have a video of one of the walking groups, or maybe one from Thursday and one from Monday to be shown during the resting phases. Since @marc-hanheide produced this video the last time, I would rely on him since I don't even know where to look for the data and how to extract the images ;)

**Comment by denisehe** [comment]
yes please

**Comment by marc-hanheide** [comment]
What precisely do you want in this video? How long?

**Comment by cdondrup** [comment]
I'd say that is up to @denisehe to decide

**Comment by denisehe** [comment]
as we saw from the video that is presented now its really very effective having them on - participants recognize themselves in the videos and are very faszinated - and that is really cognitive highly stimulating in the case of dementia
but the video is from last year with not all current participants in it
thus it would be cool to have short video sequences of the latest walking group sessions. so that was the original plan when we planned the walking group.

thus a video of a monday and a thrusday session from this years video recorings, 
in the style that is on now.
maybe 1,5-2 min per video

**Comment by marc-hanheide** [comment]
Sorry, I made several attempts to download videos for editing from Henry but failed. The problem is I only have my laptop here in Rome and either its Wifi or Henry's disconnected in transfer. I have a few other ideas on how to transfer it, but it'll take longer than expected.

**Comment by cdondrup** [comment]
Of you tell me what to do, I'll download and put it on owncloud. That at least eliminates the dodgy connection from Henry for you.

**Comment by marc-hanheide** [comment]
using rsync now to get it to UoL first. As rsync can recover from transfer errors... It'll be done at some point. But it takes ages.

**Comment by marc-hanheide** [comment]
Can you try this one: https://lcas.lincoln.ac.uk/owncloud/index.php/s/9XSMyozYN8OABw4

It's no Academy Award masterpiece but maybe useful for today.

@cdondrup can I ask you to upload it to the robot if it works?

**Comment by cdondrup** [comment]
Worked for me. Uploaded to media server and added to the walking group video set. Removed the old one.

This needs to be tested on the robot today before the start of the walking group while waiting for the participants.

**Comment by marc-hanheide** [comment]
@denisehe @TobKoer there's a video now that needs testing on the robot. Liaise with @cdondrup to test it.

**Comment by denisehe** [comment]
ok so I try before the walking group :-)

thank you!

**Comment by denisehe** [comment]
WG will start at 14:30 today - but the robot can get to his position as usual!
