### ISSUE TITLE
Walking Group Feedback

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#343]
Hi @cdondrup - I want to feed back that this years walking group deplyoment has really improved a lot compared to last year!
The failure rate was really low, the robot managed to navigate through really difficult situations quickly (like crowded corridors, monday markets on the ground floor, wheel chairs, and beds that blocked certain ways).

Furthermore it was really good that the therapists were able to chose a certain chair - so they could make better use of the entertainment function this year.

It was also really beneficial that the volume could be adjusted during walking, this was used several times!

Also the new structure of the map with areas the therapists could send the robot to was easy to use. 

So thanks a lot for all your effords besides finishing your PhD :-)
In terms of this years task evaluation it really payed off :-)

@marc-hanheide @hawesie @TobKoer

**Comment by marc-hanheide** [comment]
👏  @cdondrup well done!

**Comment by cdondrup** [comment]
I have to admit that it was more work than I hoped and that I was more annoyed than I would like to admit while doing it but I am really happy that it paid off. From observing the group I could already see that there were much less failures (this is mainly due to the increase in RAM on the machine because it was mostly at 5-6GB which is hard to achieve with 4GB we had last year ;) and of course the navigation improvements) but it is very nice to hear that from your perspective as well and knowing that the new features were received well always lifts the heart :) 

Thank you very much for running all the evaluation and rallying the support of the therapists @denisehe! I'm sure that'll be a nice paper again :P 

Due to my change in circumstances, I cannot commit to any major changes of the system till the next deployment I'm afraid but I'll try to have it in a working state for the last leg of the journey ;)
