### ISSUE TITLE
Werner/Henry needs a fan

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#345]
On order to tackle [charging issues](https://github.com/strands-project/scitos_robot/issues/72) can you please make sure to put a solution in place like this:
https://github.com/strands-project/scitos_robot/issues/72#issuecomment-228815970

**Comment by kirumang** [comment]
Werner got a fan now. 
but, the fan makes some noise.
Currently, the power source comes from the wire which connects to a network hub (also 12V)
Do I need to connect the power cable of the fan to some specific power connector or pin?

e.g. some pins that have 12V power while battery charging, otherwise no power on it,
@marc-hanheide @gestom 

![20161019_161730](https://cloud.githubusercontent.com/assets/6443097/19522703/1fc7b6c2-9653-11e6-9e09-ec98cc9b1059.jpg)

**Comment by marc-hanheide** [comment]
When you say noise, is it a problem? @gestom to comment on the wiring.

**Comment by gestom** [comment]
Hi, we connected the fan to one of the side PC's power sources. It's pretty silent.

**Comment by kirumang** [comment]
Thanks.
I don't know the noise can be a problem in the field of AAF deployment.
If the noise become a problem, I will make the fan slightly slower.
