### ISSUE TITLE
No go areas

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#346]
@Jailander @capamat-aaf @marc-hanheide 

Dear all, where are all the current no-go areas located? 

@Jailander - could you send them marked on a map? Because I am not sure if I have all in mind, and as Matei takes over STRANDS it would be good for him to know!

Thanks, Denise

**Comment by cdondrup** [comment]
I don't think there are any no go areas anymore because that never worked as expected and we had to get rid of it. 
Except for in front of stairs there are nogo nodes. So if the robot goes there it will stop and call for help. But that should be the only ones.

**Comment by denisehe** [comment]
oh ok. good to know @capamat-aaf 

and the therapy area, you know the narrow corridor in the very back? this is a no go zone right?

**Comment by Jailander** [comment]
Hi @denisehe yes @cdondrup is right there are no no-go areas, there are no go nodes which I painted in red for you on this map:
![nogonodes](https://cloud.githubusercontent.com/assets/5035967/18082860/9518da92-6e98-11e6-8773-6a8e4ad62ddc.png)

**Comment by denisehe** [comment]
ok thanks @Jailander  - but what about the nerrow corridor on the back side of the therapy wing???

this was agreed to be a no go area - as it is really nerrow with lots of people and wheelchairs.

Last year thought, the robot just moved in - to our very astonishment - as we always thought that this zone is a no go area....

so whats the status on this?

Thanks and Cheers, denise

**Comment by Jailander** [comment]
No @denisehe that area has always been transitable, the robot has just learnt not to go that way because it takes longer and there are more obstacles, as far as I can tell we never said that this area would be a no go and there are even bellbot nodes in this area, maybe I am talking about the wrong area?
I'm thinking the one in yellow here:
![nogonodes](https://cloud.githubusercontent.com/assets/5035967/18083273/52a2d152-6e9a-11e6-8790-d51a58a97989.png)

**Comment by denisehe** [comment]
@Jailander hmmm thats really very strange - caus I remember that we stated from the very beginning that the robot should never go there because its very busy and thus really undonfortable and maybe "dangerours" for the seniors waiting for therapy back there....

I dont know since when this was changed - because as far as I remember we discussed from the beginning that this area needs to be a no go zone - I never heard anything different - just now acutally ^^

**Comment by denisehe** [comment]
Could this at least be fixed for the upcoming trial? 
The robot really should not go there - also not for learning purposes!

**Comment by capamat-aaf** [comment]
Hello, first time posting here;

These are the sensitive areas that afaik have been agreed upon.
Orange is a non filming zone, because the patients receive their therapy here.
Red is a no-go area because of the therapy rooms, which is a busy area for the patients, esp. with wheelchairs and walking aids.

(didn't find the graphic software yet, so here's the picture in paint)

![aaf-dep_nogo](https://cloud.githubusercontent.com/assets/21201058/18083348/0b771424-6ea3-11e6-99da-ec6f10af42f7.png)

**Comment by denisehe** [comment]
@Jailander @marc-hanheide 
or could you indicate where the robot is not filming exactly? because as matei is new, it would be helpful if he had all these details :-)

Thanks!

**Comment by Jailander** [comment]
I can remove those nodes from the topological map yes that is no problem, but then it wouldn't go to to all the bellbot points you gave me in the beginning.
Also as far as I can remember the robot last year only went through that area during the first week (I can take a look at the data later), we explained you that the robot learnt that path because it had had many issues the other way because of the changes of nodes positions done at the last minute making nodes too close to the walls.
Once this was fixed I reset the stats and the robot learnt it correctly and I am quite confident that the robot was not an issue on that corridor, as I said changing this for the next deployment is easy but I would like to know when this was agreed because I have always included these nodes on the topological map and as I said this are was enabled for bellbot.
The no recording area can be seen in green here:
![nogonodes](https://cloud.githubusercontent.com/assets/5035967/18083811/bf358ee8-6e9c-11e6-9686-c8246b536a0b.png)

**Comment by denisehe** [comment]
I will check about this info with tobias - this really is something entirely new for me - my latest point of knowledge was that this is a no-go area - thus I was surprised that the robot was driving in there once, after a waling group session....

**Comment by Jailander** [comment]
Thank you very much @denisehe it will be useful to know where the communication was broken.

In any case, I don't think we will need to include this area for Y4 deployment, since the point for the robot learning its routes has been made already, but I still think it will be interesting to keep it now that we will be doing edge exploration too, however this will mean that the robot will go to this area at least once, so I will leave this for @marc-hanheide to negotiate ;) with whoever is there (but @denisehe will be missed greatly)

**Comment by denisehe** [comment]
Yes, I will let you know!!

Yes it will be for @capamat-aaf to discuss.

Yeah, I will really miss you all! It was a really really cool time with you and the rest of the consortium :-)

**Comment by cdondrup** [comment]
Not really helping but this is the first time I hear about this being nogo area. I only remembered that we said we don't want the walking group to go through there because the robot might get stuck.

Regarding the robot going there once after the group, I cannot remember this instance. I know that it went there once before a group due to a mislocalisation which I then fixed remotely. This wouldn't have been avoided by a no go area either, though.

**Comment by denisehe** [comment]
ähhhh what? hahaha oookaaay thats more than strange - because here it always was a no go zone.

well and actually when it drove in I pushed the bumper to get wolfgang or sergey removing it from back there - and I remember that I was really astonished, that it was going in there ^^

omg O_O

**Comment by denisehe** [comment]
@TobKoer  look Tobias.

**Comment by denisehe** [comment]
@Jailander @marc-hanheide @capamat-aaf 

hi there - i got response from tobias - he also thought that we agreed that the robot should not drive through the narrow corridor back in the therapy wing.
he said that he remembers that technical partners agreed, especially as in the first two years navigation was quite inreliable and thus we all did not want to risk any wheel chair crashes...

We also had our Werner Demo at TUW yesterday - but even colleagues there thought that back there is a no go area....

so can there anything be done to prohibit the robot in entering there for the upcoming deployment?

**Comment by marc-hanheide** [comment]
so, this needs modification of the topo map. That is a bit of a shame, but if needed we have to take the waypoints out. @gestom and @Jailander please comment if this is a problem. If not, @Jailander to modify map.

**Comment by Jailander** [comment]
Tes its a shame, but I can remove this area I think the point was made on the previous deployments

**Comment by marc-hanheide** [comment]
@Jailander to remove the 5 waypoints.
