### ISSUE TITLE
Walking Group Year 4 Deployment

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#347]
@cdondrup @marc-hanheide @capamat-aaf 

Hi there, i opened a new issue for Walking Group especially

Many thanks for your offer Christian, to monitor the Walking Groups although you being in Scotland.
:-)
The plan so far: we will offer the Walking Group Task every Monday and Thrusday throughout the deployment - but the Therapists can choose freely, if they will take him with them or not. In the end we will see the frequency of real use behaviour.

One question though: 
I learned from the therapists feedback, that the "Warte" that appears every 10-15 meters is a bit annoying as it interrupts the walking flow.
Would it be possible to skip some of them?

I think the robots stops and asks for "Weiter" shortly after the start, in the lobby, at the chappel and in the corridor in the back of the loop. 
Is it therefore possible to skip them - except for the "Weiter" in the back of the loop (close to the cow bell area)?

Other new features are not required! :-)

Cheers, Denise

**Comment by cdondrup** [comment]
Hi, this is easily done. It is just based on tags at the waypoint. By removing the tag, the wait will not be executed. Once we have the final topo map for the deployment, I can just remove all the tags except for the one at the bells.

**Comment by denisehe** [comment]
Wow - perfect :-) 
Great!

Thanks!

**Comment by marc-hanheide** [comment]
So, I understand we want this also on-demand this year. From what I understand it is meant to run according to scheduled time in the calendar, _not_ really on demand. And the sessions will be facilitated by @capamat-aaf and @kirumang 
assigned to @cdondrup for comments.

**Comment by marc-hanheide** [comment]
new starting point shall be "Kindergarten", ok @cdondrup ?

**Comment by cdondrup** [comment]
I will have to see where I hardcoded the name of the waypoint. 
- [x] Check config files
- [x] Check tags of current starting node
- [x] Check task action server which might have the waypoint as a hardcoded default
- [x] Check intermediate waypoints to see if they are before or after Kindergarten
- [x] Check route planning

In general, I would prefer not change any waypoint or move them dramatically. The walking group is highly specialised towards the topological map we had last year. Should work in principle but I can't guarantee anything. Why the change?

**Comment by cdondrup** [comment]
Walking group starting point has been changed. Please see above PR for instructions on how to update the topo map and DB.

In order to only have the robot stop and wait once during the big loop, in the final topo map remove the tag `walking_group_pause` from all waypoint except for `WayPoint61` which should be the one next to the cow bells.

I will leave this for @Jailander and reassign to him.

**Comment by Jailander** [comment]
:+1: just that then?

**Comment by cdondrup** [comment]
Easier than I thought ;)

Past-Christian's programming skills and his thoughtfulness keep on positively surprising me today ;)

**Comment by Jailander** [comment]
yes we all miss past-Christian even Linda until she passed away this morning R.I.P

**Comment by cdondrup** [comment]
She couldn't take the pain of being separated anymore I reckon.

**Comment by Jailander** [comment]
Exactly :'( we are all feeling it

**Comment by capamat-aaf** [comment]
The Monday Walking Group has been moved to Tuesday, due to many cancellations & work schedule changes

**Comment by capamat-aaf** [comment]
Update on our study plans:
We're evaluating a similar effect to the WG, but for residents who have to spend time with med students during their (social) training. 
This week we're evaluating "walking/rolling" through the facility without Henry and next week with him.
That means that next week, we need Henry and thus the usual WG won't take place.
And for this week, I won't be able to supervise the WG, however we never had any major problems this deployment so I don't think that this should be a problem.

**Comment by cdondrup** [comment]
Please, just make sure that the walking group is either a calendar event for the time slot you want it to happen or that someone is there to request it as an on-demand task.

**Comment by capamat-aaf** [comment]
Hello,
Some observations from the WG.

• I had the impression that the waypoint at "Frisoer" is in the middle of the hall? Nonetheless, that is a hotspot for problems, also because there are a lot of people present. Could I see a map of where it is? Maybe I can come up with a better location; if it is easy to move of course!
• On his way back, after passing our office, he at some point stops and display at screen-wide "Weiter" button. At fist I though it's because the therapists aren't close-by, but he does this everytime, and I just wanted to know why.
![3](https://cloud.githubusercontent.com/assets/21201058/22584145/191d60d2-e9f1-11e6-9954-8f5d79112b7d.png)

• He does this thing at the return route after pressing "Weiter" at the ambulance stop, and then continues normally.
I made a (vertical, sorry) video and a gif:
http://im2.ezgif.com/tmp/ezgif.com-043e1dbf88.gif

https://www.dropbox.com/s/b5z2seznx80ql5n/vlc-record-2017-02-03-08h46m21s-vlc-record-2017-02-02-16h04m50s-MOV_20170119_1624595.mp4-.mp4-.mp4?dl=0

**Comment by cdondrup** [comment]
* Maybe Jaime can post the current map. The main reason for the Frisoer point to be there is that the robot has to go through it. Also, it only asks if you want to continue or rest. Once you press either it will go somewhere else. If this position is not good, please move the waypoint. I don't want to run tests again with a new waypoint ;)
* Regarding the "Weiter", please see the first post in this thread by Denise.

**Comment by capamat-aaf** [comment]
Thank you, I see that it was requested by the therapist (at some point).
Whatever is possible. There aren't that many walks left, but if somethings are easy to do, it might impprove the experience a bit.
They do rest there relatively often...

**Comment by cdondrup** [comment]
Since the walking group uses its own topological map, @Jailander should be able to just move the Frisoer waypoint to (almost) wherever you want. Please liaise with him to do that.

Regarding the wait, if it is confusing and annoying for the therapists/patients, it is very easy to remove that functionality. Just let me know.
