### ISSUE TITLE
Confirmation Dialog for emergency stop

### ISSUE THREAD

**Issue by Jailander** [strands-project/aaf_deployment#389]
@marc-hanheide to implement

**Comment by marc-hanheide** [comment]
Finally... fixed in https://github.com/strands-project/strands_ui/pull/105/commits/77064b72ffd3267d2973641fa17d6c66a95b978d

This is what it looks like now @capamat-aaf in case you want to tell people:

![screenshot from 2016-12-15 16 34 15](https://cloud.githubusercontent.com/assets/1153084/21232689/6b644f7e-c2e4-11e6-9a43-eed5f1c3e393.png)

Should work fine. @Jailander you just need to update `strands_ui` (should already be one `emergency_stop` branch) and then restart it. No further changes required.

**Comment by marc-hanheide** [comment]
OK, @Jailander I have deployed this on the robot already and also tested. Works.
