### ISSUE TITLE
get Henry to TU

### ISSUE THREAD

**Issue by capamat-aaf** [strands-project/aaf_deployment#394]
Hello,

Officially the AAF deployment ends on the 28.02. and I guess Wernry has to go back to the TU.
So I wanted to inquire about transportation.

• Related question regarding the review meeting in May: will he be brought back to make a cameo appearance?
• I was also going to ask, since the HB will host a technology event on the 28.03., if Henry could make an appearance to that as well.
In these cases, perhaps it will be easier to leave him here? Of course, only if you don't need him.

**Comment by marc-hanheide** [comment]
We should be thinking about the date we want to end the deployment. As it is relatively low maintenance at the moment we may want to extend this? @hawesie @jailander @mzillich? Also there is HRI conference in Vienna 6-9 March, it could be an opportunity to invite interested parties over as an unofficial demo?

**Comment by Jailander** [comment]
I really have no problem extending it, and I had already suggested HRI could be an opportunity to show off so its a +1 from me.

**Comment by hawesie** [comment]
Fine from me too.

**Comment by capamat-aaf** [comment]
Talked to Veronika and she said it would be fine here as well.
Would still be good to know if/when the TU @mzillich @kirumang wants him back.

**Comment by mzillich** [comment]
Ok also for us. We are out of space anyway :P

**Comment by capamat-aaf** [comment]
@gestom thanks for your mail, is it ok if we move the conversation here is well? 
so that the TU guys also know the schedule, in case we decide on something.

I'm waiting for an answer from Veronika; she said she's going to talk to the board on Wernry also still running until the end of March.
We do have one director, who eg is still waiting to finalise the changes of the corner of his charging station.

As for me, I don't mind taking care of him, but I won't be able to continue evaluating.

**Comment by gestom** [comment]
Hi all,

I was wondering about the finishing date of the AAF deployment, because I wanted to know how much time there is to test other info-terminal strategies.

In particular, I wanted to run some round robin or randomized strategy at the deployment end to test if the number of interactions decreased due to neglecting the spatio-temporal distribution of interactions. Having these tests at the end of the deployment would allow us verify if the increase of interaction number was due to the habituation effects or not.

According to my records, we started on Nov 21, so right now, the robot was running for 85 days. However, we had some minor data losses, which means that we have the complete data from 83 days only.

So:

1) We end on Monday March 20 with 120 days exactly, having full data from 118 days.
2) We end on Friday 24 + weekend on the station, (126 days, 124 days of data).
3) We end on Friday March 31 with 131 days and 129 days of data, weekend on the station gives us 133 days and 131 days of data.

Please let me know which option is acceptable.

**Comment by marc-hanheide** [comment]
I would be in favour of running longer (i.e. until the end of March), to get most out of this. Please @capamat-aaf check locally and comment here on what is deemed possible.

**Comment by mzillich** [comment]
Agree, let's make the most of the deployment.
